/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"text-muted": "#6B7280",
				"surface-dim": "#131313",
				"background": "#131313",
				"on-secondary-fixed": "#001f26",
				"surface": "#131313",
				"on-secondary-container": "#00424e",
				"tertiary": "#cdbdff",
				"surface-container-highest": "#353534",
				"primary-container": "#4f46e5",
				"on-surface-variant": "#c7c4d8",
				"surface-container": "#201f1f",
				"error": "#ffb4ab",
				"on-primary-container": "#dad7ff",
				"primary": "#c3c0ff",
				"on-tertiary": "#370096",
				"on-secondary-fixed-variant": "#004e5c",
				"primary-fixed": "#e2dfff",
				"surface-container-high": "#2a2a2a",
				"primary-fixed-dim": "#c3c0ff",
				"inverse-surface": "#e5e2e1",
				"surface-bright": "#3a3939",
				"on-background": "#e5e2e1",
				"outline": "#918fa1",
				"on-tertiary-fixed": "#20005f",
				"error-container": "#93000a",
				"on-error-container": "#ffdad6",
				"glow-cyan": "rgba(6, 182, 212, 0.15)",
				"inverse-primary": "#4d44e3",
				"on-surface": "#e5e2e1",
				"on-primary": "#1d00a5",
				"on-error": "#690005",
				"tertiary-fixed": "#e8deff",
				"on-tertiary-container": "#e1d6ff",
				"surface-tint": "#c3c0ff",
				"inverse-on-surface": "#313030",
				"glow-indigo": "rgba(79, 70, 229, 0.15)",
				"secondary": "#4cd7f6",
				"glass-border": "rgba(255, 255, 255, 0.08)",
				"tertiary-container": "#6a36ec",
				"text-primary": "#F9FAFB",
				"nav-bg": "rgba(10, 10, 10, 0.6)",
				"secondary-fixed-dim": "#4cd7f6",
				"on-primary-fixed-variant": "#3323cc",
				"secondary-fixed": "#acedff",
				"on-tertiary-fixed-variant": "#4f00d0",
				"on-primary-fixed": "#0f0069",
				"glass-surface": "rgba(255, 255, 255, 0.03)",
				"tertiary-fixed-dim": "#cdbdff",
				"surface-container-lowest": "#0e0e0e",
				"on-secondary": "#003640",
				"surface-container-low": "#1c1b1b",
				"outline-variant": "#464555",
				"surface-variant": "#353534",
				"text-secondary": "#9CA3AF",
				"secondary-container": "#03b5d3"
			},
			borderRadius: {
				"DEFAULT": "0.25rem",
				"lg": "0.5rem",
				"xl": "0.75rem",
				"full": "9999px"
			},
			spacing: {
				"gutter-mobile": "20px",
				"container-max": "1100px",
				"unit": "4px",
				"card-padding": "32px",
				"section-v-padding": "128px",
				"gutter-desktop": "40px"
			},
			fontFamily: {
				"headline-md-mobile": ["Inter"],
				"headline-md": ["Inter"],
				"display-lg-mobile": ["Inter"],
				"label-mono": ["JetBrains Mono"],
				"display-lg": ["Inter"],
				"body-sm": ["Inter"],
				"body-base": ["Inter"]
			},
			fontSize: {
				"headline-md-mobile": ["28px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "300" }],
				"headline-md": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "300" }],
				"display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "300" }],
				"label-mono": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "400" }],
				"display-lg": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "300" }],
				"body-sm": ["15px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "300" }],
				"body-base": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "300" }]
			}
		},
	},
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/container-queries')
	],
}
